### ISSUE TITLE
don't know what is Netscape format cookie.txt file

### ISSUE THREAD

**Issue by aizya** [nischalsource/SafariBooks_Downloader#2]
i  am so confuse to the option '--cookie'... can you help me?

**Comment by fpigeonjr** [comment]
:+1: same. Instructions could be clearer on how to get a valid netscape format cookie.

**Comment by aizya** [comment]
@fpigeonjr i found other tools to download safari books,i will share to you if you need.

**Comment by fpigeonjr** [comment]
yes please. I am still looking for a solution @aizya.

**Comment by aizya** [comment]
@fpigeonjr  https://github.com/Sneezry/Kepler
